{"uuid": "cabfdcf8-f6a3-4ff5-8fe6-143319060fb5", "children": ["ceb2300b-c80e-4c64-84ee-9ff622016866"], "befores": [{"name": "login", "status": "passed", "start": 1594284715170, "stop": 1594284728223}], "afters": [{"name": "login::0", "status": "broken", "statusDetails": {"message": "ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。\n", "trace": "  File \"d:\\program files\\python37\\lib\\site-packages\\allure_commons\\_allure.py\", line 185, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"d:\\program files\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 796, in _teardown_yield_fixture\n    next(it)\n  File \"E:\\CDATA\\自动化测试\\Cdata_part11\\tests\\GponSfu\\conftest.py\", line 19, in login\n    ont_del(tn, PonID, OnuID, SN)\n  File \"E:\\CDATA\\自动化测试\\Cdata_part11\\src\\Gpon\\ont_auth.py\", line 1106, in ont_del\n    command_result = tn.read_until(b\"OLT(config-interface-gpon-0/0)#\", timeout=2).decode('ascii')\n  File \"d:\\program files\\python37\\lib\\telnetlib.py\", line 315, in read_until\n    self.fill_rawq()\n  File \"d:\\program files\\python37\\lib\\telnetlib.py\", line 524, in fill_rawq\n    buf = self.sock.recv(50)\n"}, "start": 1594284745657, "stop": 1594284790980}], "start": 1594284715170, "stop": 1594284790980}