{
  "uid" : "6757096d5caead9",
  "name" : "远程重启ONU",
  "fullName" : "test_onu_mgt#test_reboot_onu",
  "historyId" : "e00c38d86143966bc49cc1457efd3998",
  "time" : {
    "start" : 1594172510416,
    "stop" : 1594172541975,
    "duration" : 31559
  },
  "description" : "\n    用例描述：\n    在OLT上远程重启ONU。\n    例如：\n    ont reboot 1 1\n    ",
  "descriptionHtml" : "<pre><code>用例描述：\n在OLT上远程重启ONU。\n例如：\nont reboot 1 1\n</code></pre>\n",
  "status" : "broken",
  "statusMessage" : "RuntimeError: Issue BringPortsOnlineCommand -portlist {Port_29 Port_30 } failed: ERROR:Hardware port (//192.168.0.180/1/9) has been attached to another logical port (Port_25)",
  "statusTrace" : "login = <telnetlib.Telnet object at 0x0000023826E535C0>\n\n    @allure.feature(\"ONU远程管理\")\n    @allure.story(\"远程管理ONU\")\n    @allure.title(\"远程重启ONU\")\n    @pytest.mark.run(order=26)\n    def test_reboot_onu(login):\n        '''\n        用例描述：\n        在OLT上远程重启ONU。\n        例如：\n        ont reboot 1 1\n        '''\n        tn = login\n        with allure.step('步骤1:发现未注册的ONU。'):\n            assert autofind_onu(tn, PonID, OnuID, SN)\n        with allure.step('步骤2:在OLT上通过SN的方式将ONU注册上线。'):\n            assert auth_by_sn(tn, PonID, OnuID, Ont_Lineprofile_ID, Ont_Srvprofile_ID, SN)\n        with allure.step('步骤3:添加service_port'):\n            assert add_service_port(tn, PonID, OnuID, Gemport_ID, [2000, 4001])\n        with allure.step('步骤4:ONU的以太网口1添加NATIVE-VLAN'):\n            assert ont_native_vlan(tn, PonID, OnuID, '1', '2000')\n        with allure.step('步骤5:ONU的以太网口2添加NATIVE-VLAN'):\n            assert ont_native_vlan(tn, PonID, OnuID, '2', '4001')\n        with allure.step('步骤6:测试仪发送双向100000个报文。'):\n>           assert stream_test(stream_rate, stream_num, download_capture_num, port_location)\n\ntest_onu_mgt.py:70: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n..\\..\\src\\Gpon\\renix_test.py:83: in stream_test\n    port1, port2 = create_ports(sys_entry, port_location)\n..\\..\\src\\Gpon\\renix_test.py:19: in create_ports\n    bring_port_online_cmd.execute()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <renix_py_api.api_gen.BringPortsOnlineCommand_Autogen.BringPortsOnlineCommand object at 0x0000023826E53F60>\n\n    def execute(self):\n        args_str = ' '.join(self.args)\n        msg = 'xet-execute {} {}'.format(self.cls_name(), args_str)\n        ret, ret_msg = self._send_msg(msg)\n        if not ret:\n>           raise RuntimeError('Issue {} {} failed: {}'.format(self.cls_name(), args_str, ret_msg))\nE           RuntimeError: Issue BringPortsOnlineCommand -portlist {Port_29 Port_30 } failed: ERROR:Hardware port (//192.168.0.180/1/9) has been attached to another logical port (Port_25)\n\nd:\\program files\\python37\\lib\\site-packages\\renix_py_api\\core.py:406: RuntimeError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "sensitive_url",
    "time" : {
      "start" : 1594171380892,
      "stop" : 1594171380893,
      "duration" : 1
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 0,
    "hasContent" : false
  }, {
    "name" : "login",
    "time" : {
      "start" : 1594172497371,
      "stop" : 1594172510416,
      "duration" : 13045
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 0,
    "hasContent" : false
  }, {
    "name" : "_verify_url",
    "time" : {
      "start" : 1594171380892,
      "stop" : 1594171380892,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 0,
    "hasContent" : false
  }, {
    "name" : "_skip_sensitive",
    "time" : {
      "start" : 1594172497371,
      "stop" : 1594172497371,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 0,
    "hasContent" : false
  }, {
    "name" : "base_url",
    "time" : {
      "start" : 1594171380892,
      "stop" : 1594171380892,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 0,
    "hasContent" : false
  } ],
  "testStage" : {
    "description" : "\n    用例描述：\n    在OLT上远程重启ONU。\n    例如：\n    ont reboot 1 1\n    ",
    "status" : "broken",
    "statusMessage" : "RuntimeError: Issue BringPortsOnlineCommand -portlist {Port_29 Port_30 } failed: ERROR:Hardware port (//192.168.0.180/1/9) has been attached to another logical port (Port_25)",
    "statusTrace" : "login = <telnetlib.Telnet object at 0x0000023826E535C0>\n\n    @allure.feature(\"ONU远程管理\")\n    @allure.story(\"远程管理ONU\")\n    @allure.title(\"远程重启ONU\")\n    @pytest.mark.run(order=26)\n    def test_reboot_onu(login):\n        '''\n        用例描述：\n        在OLT上远程重启ONU。\n        例如：\n        ont reboot 1 1\n        '''\n        tn = login\n        with allure.step('步骤1:发现未注册的ONU。'):\n            assert autofind_onu(tn, PonID, OnuID, SN)\n        with allure.step('步骤2:在OLT上通过SN的方式将ONU注册上线。'):\n            assert auth_by_sn(tn, PonID, OnuID, Ont_Lineprofile_ID, Ont_Srvprofile_ID, SN)\n        with allure.step('步骤3:添加service_port'):\n            assert add_service_port(tn, PonID, OnuID, Gemport_ID, [2000, 4001])\n        with allure.step('步骤4:ONU的以太网口1添加NATIVE-VLAN'):\n            assert ont_native_vlan(tn, PonID, OnuID, '1', '2000')\n        with allure.step('步骤5:ONU的以太网口2添加NATIVE-VLAN'):\n            assert ont_native_vlan(tn, PonID, OnuID, '2', '4001')\n        with allure.step('步骤6:测试仪发送双向100000个报文。'):\n>           assert stream_test(stream_rate, stream_num, download_capture_num, port_location)\n\ntest_onu_mgt.py:70: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n..\\..\\src\\Gpon\\renix_test.py:83: in stream_test\n    port1, port2 = create_ports(sys_entry, port_location)\n..\\..\\src\\Gpon\\renix_test.py:19: in create_ports\n    bring_port_online_cmd.execute()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <renix_py_api.api_gen.BringPortsOnlineCommand_Autogen.BringPortsOnlineCommand object at 0x0000023826E53F60>\n\n    def execute(self):\n        args_str = ' '.join(self.args)\n        msg = 'xet-execute {} {}'.format(self.cls_name(), args_str)\n        ret, ret_msg = self._send_msg(msg)\n        if not ret:\n>           raise RuntimeError('Issue {} {} failed: {}'.format(self.cls_name(), args_str, ret_msg))\nE           RuntimeError: Issue BringPortsOnlineCommand -portlist {Port_29 Port_30 } failed: ERROR:Hardware port (//192.168.0.180/1/9) has been attached to another logical port (Port_25)\n\nd:\\program files\\python37\\lib\\site-packages\\renix_py_api\\core.py:406: RuntimeError",
    "steps" : [ {
      "name" : "步骤1:发现未注册的ONU。",
      "time" : {
        "start" : 1594172510417,
        "stop" : 1594172511529,
        "duration" : 1112
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "stepsCount" : 0,
      "hasContent" : false
    }, {
      "name" : "步骤2:在OLT上通过SN的方式将ONU注册上线。",
      "time" : {
        "start" : 1594172511530,
        "stop" : 1594172526481,
        "duration" : 14951
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "stepsCount" : 0,
      "hasContent" : false
    }, {
      "name" : "步骤3:添加service_port",
      "time" : {
        "start" : 1594172526481,
        "stop" : 1594172531521,
        "duration" : 5040
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "stepsCount" : 0,
      "hasContent" : false
    }, {
      "name" : "步骤4:ONU的以太网口1添加NATIVE-VLAN",
      "time" : {
        "start" : 1594172531521,
        "stop" : 1594172531728,
        "duration" : 207
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "stepsCount" : 0,
      "hasContent" : false
    }, {
      "name" : "步骤5:ONU的以太网口2添加NATIVE-VLAN",
      "time" : {
        "start" : 1594172531728,
        "stop" : 1594172531888,
        "duration" : 160
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "stepsCount" : 0,
      "hasContent" : false
    }, {
      "name" : "步骤6:测试仪发送双向100000个报文。",
      "time" : {
        "start" : 1594172531888,
        "stop" : 1594172541974,
        "duration" : 10086
      },
      "status" : "broken",
      "statusMessage" : "RuntimeError: Issue BringPortsOnlineCommand -portlist {Port_29 Port_30 } failed: ERROR:Hardware port (//192.168.0.180/1/9) has been attached to another logical port (Port_25)\n",
      "statusTrace" : "  File \"E:\\CDATA\\自动化测试\\Cdata_part11\\tests\\GponSfu\\test_onu_mgt.py\", line 70, in test_reboot_onu\n    assert stream_test(stream_rate, stream_num, download_capture_num, port_location)\n  File \"E:\\CDATA\\自动化测试\\Cdata_part11\\src\\Gpon\\renix_test.py\", line 83, in stream_test\n    port1, port2 = create_ports(sys_entry, port_location)\n  File \"E:\\CDATA\\自动化测试\\Cdata_part11\\src\\Gpon\\renix_test.py\", line 19, in create_ports\n    bring_port_online_cmd.execute()\n  File \"d:\\program files\\python37\\lib\\site-packages\\renix_py_api\\core.py\", line 406, in execute\n    raise RuntimeError('Issue {} {} failed: {}'.format(self.cls_name(), args_str, ret_msg))\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "stepsCount" : 0,
      "hasContent" : true
    } ],
    "attachments" : [ {
      "uid" : "fb1e5109ad38142f",
      "name" : "log",
      "source" : "fb1e5109ad38142f.txt",
      "type" : "text/plain",
      "size" : 276
    } ],
    "parameters" : [ ],
    "attachmentsCount" : 1,
    "shouldDisplayMessage" : true,
    "stepsCount" : 6,
    "hasContent" : true
  },
  "afterStages" : [ {
    "name" : "login::0",
    "time" : {
      "start" : 1594172542017,
      "stop" : 1594172553164,
      "duration" : 11147
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 0,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "feature",
    "value" : "ONU远程管理"
  }, {
    "name" : "story",
    "value" : "远程管理ONU"
  }, {
    "name" : "suite",
    "value" : "test_onu_mgt"
  }, {
    "name" : "host",
    "value" : "DESKTOP-2JV12RE"
  }, {
    "name" : "thread",
    "value" : "14920-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "test_onu_mgt"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ {
      "uid" : "bd62e333dcf81815",
      "status" : "broken",
      "statusDetails" : "TypeError: 'bool' object is not subscriptable",
      "time" : {
        "start" : 1594171020582,
        "stop" : 1594171020582,
        "duration" : 0
      }
    }, {
      "uid" : "d0823dae05435412",
      "status" : "failed",
      "statusDetails" : "AssertionError: assert False\n +  where False = autofind_onu(<telnetlib.Telnet object at 0x000002E21D382BE0>, '16', '2', '5A54453171200033')",
      "time" : {
        "start" : 1594127953279,
        "stop" : 1594128012760,
        "duration" : 59481
      }
    }, {
      "uid" : "5806f19158ee6028",
      "status" : "broken",
      "statusDetails" : "RuntimeError: Issue BringPortsOnlineCommand -portlist {Port_29 Port_30 } failed: ERROR:Hardware port (//192.168.0.180/1/9) has been attached to another logical port (Port_25)",
      "time" : {
        "start" : 1594122677762,
        "stop" : 1594122713095,
        "duration" : 35333
      }
    }, {
      "uid" : "fd55b6c3c8c5caff",
      "status" : "failed",
      "statusDetails" : "AssertionError: assert False\n +  where False = autofind_onu(<telnetlib.Telnet object at 0x0000027E35745160>, '16', '2', '5A54453171200033')",
      "time" : {
        "start" : 1594112742411,
        "stop" : 1594112747525,
        "duration" : 5114
      }
    }, {
      "uid" : "65a5a707954b1c42",
      "status" : "failed",
      "statusDetails" : "AssertionError: assert False\n +  where False = auth_by_sn(<telnetlib.Telnet object at 0x00000208E292E710>, '16', '2', '200', '200', '5A54453171200033')",
      "time" : {
        "start" : 1594037348019,
        "stop" : 1594037411156,
        "duration" : 63137
      }
    }, {
      "uid" : "37c2dab069c1c6a8",
      "status" : "failed",
      "statusDetails" : "AssertionError: assert False\n +  where False = auth_by_sn(<telnetlib.Telnet object at 0x00000208E291DBA8>, '16', '2', '200', '200', '5A54453171200033')",
      "time" : {
        "start" : 1594037260036,
        "stop" : 1594037323860,
        "duration" : 63824
      }
    }, {
      "uid" : "6660c2adfae20fa1",
      "status" : "failed",
      "statusDetails" : "AssertionError: assert False\n +  where False = auth_by_sn(<telnetlib.Telnet object at 0x00000208E2936320>, '16', '2', '200', '200', '5A54453171200033')",
      "time" : {
        "start" : 1594037171896,
        "stop" : 1594037235860,
        "duration" : 63964
      }
    }, {
      "uid" : "2c21af95e861063c",
      "status" : "passed",
      "time" : {
        "start" : 1594005521926,
        "stop" : 1594005663521,
        "duration" : 141595
      }
    }, {
      "uid" : "f8476aa3333e73cf",
      "status" : "passed",
      "time" : {
        "start" : 1594004569893,
        "stop" : 1594004720825,
        "duration" : 150932
      }
    }, {
      "uid" : "1dc56cb442d861e3",
      "status" : "broken",
      "statusDetails" : "Exception: bring online port(Port_1) failed",
      "time" : {
        "start" : 1594003578663,
        "stop" : 1594003632175,
        "duration" : 53512
      }
    }, {
      "uid" : "bad49a061c352714",
      "status" : "failed",
      "statusDetails" : "AssertionError: assert False\n +  where False = stream_test('10', '100000', '10000', ['//192.168.0.180/1/9', '//192.168.0.180/1/10'])",
      "time" : {
        "start" : 1594001301002,
        "stop" : 1594001346405,
        "duration" : 45403
      }
    }, {
      "uid" : "cd6a7a24b1116134",
      "status" : "broken",
      "statusDetails" : "RuntimeError: Issue BringPortsOnlineCommand -portlist {Port_27 Port_28 } failed: ERROR:Hardware port (//192.168.0.180/1/9) has been attached to another logical port (Port_23)",
      "time" : {
        "start" : 1593771975666,
        "stop" : 1593772008606,
        "duration" : 32940
      }
    } ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "6757096d5caead9.json",
  "parameterValues" : [ ]
}