[32mINFO    [0m CDATA:Cdata_loggers.py:106 192.168.3.138 登录成功
[32mINFO    [0m CDATA:Cdata_loggers.py:106 =========ONU业务测试：PPPOE拨号测试=========
[32mINFO    [0m CDATA:Cdata_loggers.py:106 ONU在OLT上被重新被发现。
[32mINFO    [0m CDATA:Cdata_loggers.py:106 当前ONU_ID没有被占用。
[32mINFO    [0m CDATA:Cdata_loggers.py:106 ==========================================
[31m[1mERROR   [0m CDATA:Cdata_loggers.py:98 ===============ERROR!!!===================
[31m[1mERROR   [0m CDATA:Cdata_loggers.py:98 ONU在OLT上添加失败。
[32mINFO    [0m CDATA:Cdata_loggers.py:106 ==========================================
[32mINFO    [0m CDATA:Cdata_loggers.py:106 ONU在OLT上删除成功
[32mINFO    [0m CDATA:Cdata_loggers.py:106 ONU在OLT上被重新被发现。